### ISSUE TITLE
Support forum / discord?

### ISSUE THREAD

**Issue by lostpebble** [Logflare/logflare#1155]
Hi,

We've just started using the product today. I am a little surprised at how shallow the documentation is, and how its very hard to find basic answers to things just searching online.

Is there any chance that there is a discord or some other kind of "immediate" and community-engaged support forum?

At the moment, we're trying to make sure our BigQuery tables have no TTL- but it seems we _have to_ set a TTL on a backend. Is there any way around this? Also, Data Studio gives errors when trying to query data on our backend- something about partition filters on "timestamp", but I couldn't immediately find a way to resolve this.

Also, we weren't able to target "europe-west1" for our BigQuery. It just kept saying that the dataset location wasn't supported, but in the linked webpage, it clearly is one of the regions. I eventually had to settle for just "EU".

**Comment by lostpebble** [comment]
![image](https://user-images.githubusercontent.com/1508863/185736964-345651f2-7962-4c0d-8f2a-d5e7b1e24b08.png)

![image](https://user-images.githubusercontent.com/1508863/185736974-152ee81e-c25b-4688-8c4c-0df730979cc0.png)

Also getting inconsistencies like this, and wondering if its something  we're doing wrong? Clearly the schema field _does_ exist exactly where it says it does not.

**Comment by lostpebble** [comment]
![image](https://user-images.githubusercontent.com/1508863/185737556-a36899af-2d25-4e9f-90d3-d643adf4a13d.png)

Looks like metadata is inconsistently being pushed to our BigQuery table as well. Sometimes its just completely `null` ...

Overall, this is a little worrying and its making the product feel a little incomplete. We mostly just wanted an easy endpoint to inject metadata with automated schema updates into BigQuery.

**Comment by lostpebble** [comment]
After hitting the endpoint a few more times, it seems like the `null` issue has stopped, perhaps it was just the initial few while the schema was being hydrated in the system.

**Comment by Ziinc** [comment]
@lostpebble the schema does take some time to update across the cluster as the schema update is triggered async from the initial schema change detection (in order to prevent event insertion backlog), hence the nulls would only occur on the first few events.

If there are further issues relating to the insertions do let me know and I will investigate.

There are currently no plans for a support forum or discord, the next best option would be to post your questions here (which will eventually get looked at by me or @chasers ). If it is urgent and affects your paid plan, you may create a ticket through the supabase [support channels](https://supabase.com/support) which will get escalated to us.
