### ISSUE TITLE
Custom Event Message doesn't affect all messages

### ISSUE THREAD

**Issue by Sxxov** [Logflare/logflare#1691]
I'm using Logflare via Vercel. (v1.4.1 on https://logflare.app)

Since [Vercel wraps the message](https://vercel.com/integrations/logflare#:~:text=Vercel%20wraps%20all,the%20stdout%20string.) & I only really care about the contents of the `console.log`s anyways, I've set a Custom Event Message to target the `metadata.message` part of a log:

<img width="443" alt="image" src="https://github.com/Logflare/logflare/assets/50891910/f6db56a9-d089-4365-8441-8a93e1250da2">

However, I've noticed that it doesn't apply to all of the log messages I see in the console. You can see in the image below, all the long messages (everything starting with `edge`) are supposed to have been replaced with their contents.

<img width="757" alt="image" src="https://github.com/Logflare/logflare/assets/50891910/aa5306e9-1551-4fdc-80e0-1c459b6ae43a">

I think it happens more often when I send logs more often? Almost like it's only affecting the first log out of a clump of multiple logs sent very closely together, but I'm not really sure.

Any help on this would be greatly appreciated, & let me know if I can provide more information on this.

**Comment by Ziinc** [comment]
This is due to vercel truncation of log lines, as has been warned in the documentation here
https://docs.logflare.app/integrations/vercel/#logging-a-custom-json-object

Truncated log lines cannot be parsed on the Logflare side, and hence result in the default text being shown in your ss.

it is advised to use [pino + pino-logflare](https://github.com/Logflare/pino-logflare) for more structured logging.
